# Generated by Django 3.2.16 on 2023-10-23 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monster", "0002_auto_20221226_2153"),
    ]

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monsterA",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="monster.monster",
                        verbose_name="Monster A",
                    ),
                ),
                (
                    "monsterB",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="monster.monster",
                        verbose_name="Monster B",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="monster.monster",
                        verbose_name="Winner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Battle",
                "verbose_name_plural": "Battles",
                "ordering": ["id"],
            },
        ),
    ]
